#This not project version docker version
version: '3.8'
#creating volumes but volume name any use in service only creared 
volumes:
  #vol_name
  sample:
#here always can use containser name add .but n8n, enginex,keyclock like third party service only make a conatiner
#internal microserve mostly dicripce by docker image always direcly use docker.file
#service name->it is every container each name gives.its give to constant name if container ip change also can use this service
##name commucate one container to another.so developer domt care about container ip change
#build: ->direclty build diecly create container using docker file
#image: ->(docker,amazon,google) registery or docker local folder
services:
  #Each 
  #service name
  centerl:
    volumes:
        #create into project folderName+app like metains
      - sample:/app/aop/logger
    #Warning:docker image file any change made you should change image version other vice not create image and container
    build: 
      context: .
      #development or prodction env
      target: ${environment}
      #args give specially like ${developerName} env variable for .env this devlper name via arus tranfer to docker image
      args:
        - developerName=${developerName}
        - version=${version}
    #this provide docker file builded image name.
    #without build command use this automatically search image name on local the docker hub.if not avaiable gives error
    image: "${serviceName}:${version}"
    #here only can use -
    container_name: "${serviceName}-${environment}-${version}"
    #warning: carful same time dev container run give error in docker reason both are run to try same port number
    ports:
      - "${port}:${port}" 
  # keyclock:
  #   #cannot rename this imagename.reason this is pulled by image name
  #   image: quay.io/keycloak/keycloak:latest
  #   container_name: "keyclock"
  #   # container_name: keycloak
  #   #commond for during running conatiner.its control envrioment(prod,dev) or database change or config mode change
  #   # example you ave config 1,config 2,config 3 both 3 are run without  
  #   command: start-dev
  #   environment:
  #     # Database configuration (example using internal H2 for dev, replace with Postgres for production)
  #     #dev-mem internal memmory
  #     KC_DB: dev-mem
      
  #     # Admin credentials
  #     KEYCLOAK_ADMIN: admin
  #     KEYCLOAK_ADMIN_PASSWORD: 1234
      
  #     # URL configuration
  #     KC_HOSTNAME: localhost
  #     #external port unick for each container can customiple .without external port that app only container inside.that inside can see only that terminal console can see
  #     ## without external port using container ip only send requset server 
  #     #internal port image provider give option only can change(in express app.listnen port) 
  #     #this caller port mapping
  #   ports:
  #     - "8080:8080"
  #   restart: unless-stopped


